runtime: nodejs
env: flex

endpoints_api_service:
  # The following values are to be replaced by information from the output of
  # 'gcloud endpoints services deploy openapi-appengine.yaml' command.
  name: mcc-fall-2019-g20.appspot.com
  rollout_strategy: managed
